### ISSUE TITLE
Nested objects are deserialized as dictionaries instead of actual object

### ISSUE THREAD

**Issue by alexanderilyin** [rnag/dataclass-wizard#115] opened 2024-04-10 06:49 UTC
* Dataclass Wizard version: 0.22.3
* Python version: Python 3.11.8
* Operating System: Ubuntu 20.04.6 LTS

### Description

You should be able to reproduce problem with [A (More) Complete Example](https://dataclass-wizard.readthedocs.io/en/latest/examples.html#a-more-complete-example). This leads to problems when you start working with deserialized result but instead of expected objects there are dicts.

### Expected

```python
…
c = MyTestClass.from_dict(data)

print(repr(c))
# prints the following result on a single line:
#   MyTestClass(
#       my_ledger={'Day 1': 'some details', 'Day 17': ['a', 'sample', 'list']},
#       the_answer_to_life=42,
#       people=[
#           Person(
#               name=Name(first='Roberto', last='Fuirron', salutation='Mr.'),
#               age=21, birthdate=datetime.datetime(1950, 2, 28, 17, 35, 20, tzinfo=datetime.timezone.utc),
#               gender='M', occupation=['sailor', 'fisher'],
#               hobbies=defaultdict(<class 'list'>, {'M-F': ['chess', '123', 'reading'], 'Sat-Sun': ['parasailing']})
#           ),
#           Person(
#               name=Name(first='Janice', last='Darr', salutation='Dr.'),
#               age=45, birthdate=datetime.datetime(1971, 11, 5, 5, 10, 59),
#               gender='F', occupation='Dentist',
#               hobbies=defaultdict(<class 'list'>, {})
#           )
#       ], is_enabled=True)

```

### Actual

```python
…
c = MyTestClass.from_dict(data)

print(repr(c))
#   MyTestClass(
#       my_ledger={'Day 1': 'some details', 'Day 17': ['a', 'sample', 'list']},
#       the_answer_to_life=42,
#       people=[
#           {
#               'name': ('Roberto', 'Fuirron'),
#               'age': 21,
#               'birthdate': '1950-02-28T17:35:20Z',
#               'gender': 'M',
#               'occupation': ['sailor', 'fisher'],
#               'Hobbies': {'M-F': ('chess', 123, 'reading'), 'Sat-Sun': ['parasailing']}
#           }, {
#               'name': ('Janice', 'Darr', 'Dr.'), 
#               'age': 45, 
#               'birthdate': '1971-11-05 05:10:59', 
#               'gender': 'F', 
#               'occupation': 'Dentist'
#           }], is_enabled=True)

```

**Comment by alexanderilyin** [comment] 2024-04-10 07:35
For now had to switch to [`dataclasses-json`](https://pypi.org/project/dataclasses-json/) and use this for my particular use case:

* https://github.com/lidatong/dataclasses-json/issues/187#issuecomment-919992503

For now I have this:

```python
@dataclass
class Artifact(JSONWizard):
  class _(JSONWizard.Meta):
    skip_defaults = True
```

Instead of:

```python
@dataclass_json
@dataclass
class Artifact(Mixin):
  pass
```

IDK what's causing this but I'm pretty sure it worked. Probably will need to write a test for this 1st so it's easy to reproduce and then will try to fix it.

**Comment by rnag** [comment] 2024-11-24 03:50
@alexanderilyin I am not sure... this seems a _very_ strange issue. I am not sure if it's due to the Ubuntu, but I haven't been able to reproduce it.

Tested with:
* Dataclass Wizard version: 0.22.3
* Python version: Python 3.11.8
* Operating System: Mac OS Sequoia 15.1 (24B83)

---

For provided code:

```python3
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, Literal, Union, Any, NamedTuple

from dataclass_wizard import JSONSerializable


@dataclass
class MyTestClass(JSONSerializable):
    my_ledger: dict[str, Any]
    the_answer_to_life: Optional[int]
    people: list['Person']
    is_enabled: bool = True


@dataclass
class Person:
    name: 'Name'
    age: int
    birthdate: datetime
    gender: Literal['M', 'F', 'N/A']
    occupation: Union[str, list[str]]
    hobbies: defaultdict[str, list[str]] = field(
        default_factory=lambda: defaultdict(list))


class Name(NamedTuple):
    """A person's name"""
    first: str
    last: str
    salutation: Optional[Literal['Mr.', 'Mrs.', 'Ms.', 'Dr.']] = 'Mr.'


data = {
    'myLedger': {
        'Day 1': 'some details',
        'Day 17': ['a', 'sample', 'list']
    },
    'theAnswerTOLife': '42',
    'People': [
        {
            'name': ('Roberto', 'Fuirron'),
            'age': 21,
            'birthdate': '1950-02-28T17:35:20Z',
            'gender': 'M',
            'occupation': ['sailor', 'fisher'],
            'Hobbies': {'M-F': ('chess', 123, 'reading'), 'Sat-Sun': ['parasailing']}
        },
        {
            'name': ('Janice', 'Darr', 'Dr.'),
            'age': 45,
            'birthdate': '1971-11-05 05:10:59',
            'gender': 'F',
            'occupation': 'Dentist'
        }
    ]
}

c = MyTestClass.from_dict(data)

print(repr(c))
```

I get the correct/intended output:

```
MyTestClass(my_ledger={'Day 1': 'some details', 'Day 17': ['a', 'sample', 'list']}, the_answer_to_life=42, people=[Person(name=Name(first='Roberto', last='Fuirron', salutation='Mr.'), age=21, birthdate=datetime.datetime(1950, 2, 28, 17, 35, 20, tzinfo=datetime.timezone.utc), gender='M', occupation=['sailor', 'fisher'], hobbies=defaultdict(<class 'list'>, {'M-F': ['chess', '123', 'reading'], 'Sat-Sun': ['parasailing']})), Person(name=Name(first='Janice', last='Darr', salutation='Dr.'), age=45, birthdate=datetime.datetime(1971, 11, 5, 5, 10, 59), gender='F', occupation='Dentist', hobbies=defaultdict(<class 'list'>, {}))], is_enabled=True)
```

**Comment by rnag** [comment] 2024-11-24 03:53
> For now had to switch to [`dataclasses-json`](https://pypi.org/project/dataclasses-json/) and use this for my particular use case:
> 
> * [Efficient way to skip encoding null optionals? lidatong/dataclasses-json#187 (comment)](https://github.com/lidatong/dataclasses-json/issues/187#issuecomment-919992503)
> 
> For now I have this:
> 
> ```python
> @dataclass
> class Artifact(JSONWizard):
>   class _(JSONWizard.Meta):
>     skip_defaults = True
> ```
> 
> Instead of:
> 
> ```python
> @dataclass_json
> @dataclass
> class Artifact(Mixin):
>   pass
> ```
> 
> IDK what's causing this but I'm pretty sure it worked. Probably will need to write a test for this 1st so it's easy to reproduce and then will try to fix it.

There is already an outstanding issue on the same.

Please see/follow #80 -- this is next up on my list of features to implement (I agree it would be super nice to have!

In any case, I am closing this issue as I haven't been able to reproduce it. Please re-open if you do experience it again. Again, do follow the linked issue as I am planning to support that "conditional *skip if*" for serialization of certain fields.

Thanks!

**Closed by rnag** 2024-11-24 03:53 UTC
