### ISSUE TITLE
Python 3.11 regression and more informative parser error traceback

### ISSUE THREAD

**Issue by lmmx** [rnag/dataclass-wizard#89] opened 2023-06-03 00:38 UTC
* Dataclass Wizard version: 0.22.2
* Python version: 3.11
* Operating System: Linux

### Description

I've been using this library a lot and had noticed that I get an error concerning `Any` (either explicitly or implicit in plain `list` or `dict` type annotations).

I tried to reproduce the error and noticed that it only occurs in Python 3.11, so it's in fact a regression not a feature in need of upgrade.

### What I Did

```py
from dataclasses import dataclass
from typing import Optional

from dataclass_wizard import JSONWizard


@dataclass
class Schema(JSONWizard):
    a: Optional[list] = None


s = Schema.from_json("{}")
print(s)
```

Fails with

```py
Traceback (most recent call last):
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/loaders.py", line 532, in fromdict
    load = _CLASS_TO_LOAD_FUNC[cls]
           ~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: <class '__main__.Schema'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/louis/dev/testing/jsonwizard/error_demo.py", line 12, in <module>
    s = Schema.from_json("{}")
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/serial_json.py", line 48, in from_json
    return fromdict(cls, o) if isinstance(o, dict) else fromlist(cls, o)
           ^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/loaders.py", line 534, in fromdict
    load = load_func_for_dataclass(cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/loaders.py", line 581, in load_func_for_dataclass
    field_to_parser = dataclass_field_to_load_parser(cls_loader, cls, config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/class_helper.py", line 120, in dataclass_field_to_load_parser
    return _setup_load_config_for_cls(cls_loader, cls, config, save)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/class_helper.py", line 189, in _setup_load_config_for_cls
    name_to_parser[f.name] = cls_loader.get_parser_for_annotation(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/loaders.py", line 351, in get_parser_for_annotation
    return OptionalParser(
           ^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/parsers.py", line 156, in __post_init__
    self.parser: AbstractParser = get_parser(self.base_type, cls, extras)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/loaders.py", line 412, in get_parser_for_annotation
    return IterableParser(
           ^^^^^^^^^^^^^^^
  File "<string>", line 5, in __init__
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/parsers.py", line 285, in __post_init__
    self.elem_parser = get_parser(elem_type, cls, extras)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/loaders.py", line 437, in get_parser_for_annotation
    raise ParseError(
dataclass_wizard.errors.ParseError: Failure parsing field `None` in class `None`. Expected a type Any, got NoneType.
  value: None
  error: Provided type is not currently supported.
  unsupported_type: typing.Any
```

I noticed that the error says

> dataclass_wizard.errors.ParseError: Failure parsing field `None` in class `None`. Expected a type Any, got NoneType.

This is unusual because it reports the field and class as `None` (the field is `a` and the class is `Schema`).

I took a look in `loaders.py` but it seems to be raising a level below anywhere that the `list` annotation is handled so I'm not sure what to suggest to fix it, but thought I should notify you

**Edit** I looked more closely and I think the part which could have named the field in question is

```py
File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/class_helper.py", line 120, in dataclass_field_to_load_parser
    return _setup_load_config_for_cls(cls_loader, cls, config, save)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/dcw/lib/python3.11/site-packages/dataclass_wizard/class_helper.py", line 189, in _setup_load_config_for_cls
    name_to_parser[f.name] = cls_loader.get_parser_for_annotation(
```

Dropping into PDB with a breakpoint:

```py
def dataclass_field_to_load_parser(
    cls_loader: Type[AbstractLoader], cls: Type, config: M, save: bool = True
) -> "DictWithLowerStore[str, AbstractParser]":
    """
    Returns a mapping of each lower-cased field name to its annotated type.
    """
    breakpoint()
    if cls not in _FIELD_NAME_TO_LOAD_PARSER:
        return _setup_load_config_for_cls(cls_loader, cls, config, save)

    return _FIELD_NAME_TO_LOAD_PARSER[cls]
```

then continuing with `unt 181` to get into `_setup_load_config_for_cls` shows the values that would be informative for a traceback:

```py
(Pdb) p cls
<class '__main__.Schema'>
(Pdb) p f
Field(name='a',type=typing.Optional[list],default=None,default_factory=<dataclasses._MISSING_TYPE object at 0x7fbdade278d0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=False,_field_type=_FIELD)
```

Maybe a try/except could catch any ParserErrors here and make them more interpretable (at the risk of chaining yet another traceback exception!)

My suggestion then would be to put

```py
        try:
            name_to_parser[f.name] = cls_loader.get_parser_for_annotation(
                field_type, cls, field_extras
            )
        except:
            raise ValueError(
                f"Error getting parser for {cls.__name__}.{f.name}: {field_type}"
            )
```

here:

https://github.com/rnag/dataclass-wizard/blob/e3fe0760422613eaf79e0236840a50f27caec064/dataclass_wizard/class_helper.py#L189-L191

which gives

> ValueError: Error getting parser for Schema.a: typing.Optional[list]

at the end of 

```py
Traceback (most recent call last):
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/loaders.py", line 532, in fromdict
    load = _CLASS_TO_LOAD_FUNC[cls]
           ~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: <class '__main__.Schema'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/class_helper.py", line 182, in _setup_load_config_for_cls
    name_to_parser[f.name] = cls_loader.get_parser_for_annotation(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/loaders.py", line 351, in get_parser_for_annotation
    return OptionalParser(
           ^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/parsers.py", line 156, in __post_init__
    self.parser: AbstractParser = get_parser(self.base_type, cls, extras)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/loaders.py", line 412, in get_parser_for_annotation
    return IterableParser(
           ^^^^^^^^^^^^^^^
  File "<string>", line 5, in __init__
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/parsers.py", line 285, in __post_init__
    self.elem_parser = get_parser(elem_type, cls, extras)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/loaders.py", line 437, in get_parser_for_annotation
    raise ParseError(
dataclass_wizard.errors.ParseError: Failure parsing field `None` in class `None`. Expected a type Any, got NoneType.
  value: None
  error: Provided type is not currently supported.
  unsupported_type: typing.Any

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/louis/dev/testing/jsonwizard/error_demo.py", line 12, in <module>
    s = Schema.from_json("{}")
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/serial_json.py", line 48, in from_json
    return fromdict(cls, o) if isinstance(o, dict) else fromlist(cls, o)
           ^^^^^^^^^^^^^^^^
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/loaders.py", line 534, in fromdict
    load = load_func_for_dataclass(cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/loaders.py", line 581, in load_func_for_dataclass
    field_to_parser = dataclass_field_to_load_parser(cls_loader, cls, config)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/class_helper.py", line 114, in dataclass_field_to_load_parser
    return _setup_load_config_for_cls(cls_loader, cls, config, save)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/dev/testing/jsonwizard/repo/dataclass_wizard/class_helper.py", line 186, in _setup_load_config_for_cls
    raise ValueError(
ValueError: Error getting parser for Schema.a: typing.Optional[list]
```

There are 2 issues here then, the regression and the uninformative error message, I'll rename my issue

**Comment by mschiedon** [comment] 2023-07-19 12:07
I'm experiencing the same or a similar enough issue as described above by Louis.

So I debugged the differences in flow between Python 3.10.6 and Python 3.11.0rc1 on Ubuntu 22.04.

The outcome of the conditional statement on [line 279](https://github.com/rnag/dataclass-wizard/blob/e3fe0760422613eaf79e0236840a50f27caec064/dataclass_wizard/loaders.py#L279C33-L279C33), where it says `if isinstance(base_type, type)`, is different between the two Python versions for `typing.Any`. Haven't yet looked at the 'why' and don't completely understand what that particular line in `loaders.py` should achieve, but the difference is clear and it can be easily verified:

## Python 3.10.6

```bash
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import typing
>>> isinstance(typing.Any, type)
False
```

## Python 3.11.0rc1

```bash
Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import typing
>>> isinstance(typing.Any, type)
True
```

Therefore, on Python 3.11 the code on [line 320](https://github.com/rnag/dataclass-wizard/blob/e3fe0760422613eaf79e0236840a50f27caec064/dataclass_wizard/loaders.py#L320), which checks if `base_type is Any` is never hit, and this eventually results in the exception on [line 436](https://github.com/rnag/dataclass-wizard/blob/e3fe0760422613eaf79e0236840a50f27caec064/dataclass_wizard/loaders.py#L436) being raised.

**Comment by mschiedon** [comment] 2023-07-19 12:10
For reference, I used the following minimal example code to reproduce the issue:

```python
from dataclasses import dataclass

from dataclass_wizard import JSONSerializable


@dataclass
class Item(JSONSerializable):
    data: dict


print(Item.from_json('{"data": {}}'))
```

**Comment by balintbako-d4t4** [comment] 2024-01-03 14:35
I had the same issue and my problem was solved by using typed lists.
I was using _list_ and changed those to _List[str]_ which resolved the issue.
I would expect the same to work for _dict_ as well.

E.g.

```
from dataclasses import dataclass
from typing import Optional
from dataclass_wizard import JSONWizard

@dataclass
class Schema(JSONWizard):
    a: Optional[List[str]] = None

s = Schema.from_json("{}")
print(s)
```

**Comment by rnag** [comment] 2024-11-09 21:09
@lmmx Thanks for opening this issue. Apologies for the delay in getting back, as I've been busy with life. I finally got a chance to test this out. However, I have been unable to reproduce - @mschiedon I also ran the exact code you had, and was not able to replicate the issue.

I tested with the following versions on my laptop running Mac OS X: 3.10.6, 3.11.0, 3.11.5, 3.11.10. All were successful.

Sample output below:

```
Python 3.11.0 (main, Nov  9 2024, 14:13:04) [Clang 16.0.0 (clang-1600.0.26.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dataclasses import dataclass
>>>
>>> from dataclass_wizard import JSONSerializable
>>>
>>>
>>> @dataclass
... class Item(JSONSerializable):
...     data: dict
...
>>>
>>> print(Item.from_json('{"data": {}}'))
{
  "data": {}
}
>>>
```

I included a test case that covers everything discussed in this issue, as part of #139, and will add it to the main branch so the test case can run for (the latest release of) supported Python versions.

I am closing this issue, however, as I have been unable to reproduce it on my end. I suspect the reproducibility issue is due to other unrelated changes that have been added since.

Also, thanks for the tip @balintbako-d4t4 -- strongly agree with you that using type annotations like `list[str]` over a generic `list`, should help prevent issues like this going forward, and also seems to be a good practice in general.

As always, please feel free to re-open the issue if anything related is discovered. Thanks!

**Closed by rnag** 2024-11-09 21:09 UTC
